### ISSUE TITLE
When answering the XO game , it failes whoever there're empty boxes 

### ISSUE THREAD

**Issue by MNenaey** [ARPU-PLUS/Orange_InstantWin#70]
![image](https://user-images.githubusercontent.com/44364394/56082340-18cfac00-5e18-11e9-851d-0ae2fdc1b5ed.png)

**Comment by programmerrafik** [comment]
Dear mohammed 
i think in this time  computer is win because  you answered in wrong space and he answer in last correct space so he win. 
mo matter you fial when empty boxes because some times computer win before boxes filled.

**Comment by MNenaey** [comment]
it fails sometimes in the second move not the third one

**Comment by programmerrafik** [comment]
Dear Mohammed i will check it again and update you
