### ISSUE TITLE
The draw option (no one wins) always gives me a wrong answer which is not logic

### ISSUE THREAD

**Issue by MNenaey** [ARPU-PLUS/Orange_InstantWin#71]

**Comment by programmerrafik** [comment]
dear mohammed 
you is right but we put this question as a killer question or in other word i don't wont this user to win.
so if he answered wrong or draw status i consider he is loss because he must answer correct answer only to win .

**Comment by MNenaey** [comment]
My only concern here is the user will feel that we're cheating him , it's not about the function works or not

**Comment by programmerrafik** [comment]
yes i fully agree with you . i will check this point again with nagib and update you with new
