### ISSUE TITLE
Cannot win the XO game

### ISSUE THREAD

**Issue by MNenaey** [ARPU-PLUS/Orange_InstantWin#72]

**Comment by programmerrafik** [comment]
dear Mohammed 
yes . because we put this question as a killer in another  word this question will apear only for user if we want him not win

**Comment by MNenaey** [comment]
Agree with you but do you mean that I cannot win anyway or there's a way ?
if there's a way please tell me how as I must cover all the possibilities

**Comment by programmerrafik** [comment]
no you can't win ! because this question is consider killer question
and it is static game you c an't win you can only to draw or loss.
