### ISSUE TITLE
When clicking on subscribe , nothing happened

### ISSUE THREAD

**Issue by MNenaey** [ARPU-PLUS/Orange_InstantWin#88]
![image](https://user-images.githubusercontent.com/44364394/57225572-1292b100-700d-11e9-970d-8b00924d7997.png)

**Comment by Naguib-ARPU** [comment]
It works only on mobile.
@MNenaey did you tested it from mobile or desktop?

**Comment by MNenaey** [comment]
works on both web and mobile now
